DROP TABLE IF EXISTS USUARIOS;


CREATE TABLE USUARIOS
(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    cpf_cnpj VARCHAR(255) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    senha VARCHAR(255) NOT NULL,
    perfil VARCHAR(255) NOT NULL,
    instante_criacao DATETIME NOT NULL DEFAULT NOW(),
    dinheiro DECIMAL(12, 2) NOT NULL DEFAULT 0.0
);